cartesian_trajectory_generator:
  pose_topic: /bh/CartesianImpedance_trajectory_controller/target_pose
  goal_topic: /bh/CartesianImpedance_trajectory_controller/goal
  frame_name: world
  ee_link: bh_link_ee
  publish_rate: 100
  trans_v_max: 0.5
  rot_v_max: 0.5
  trans_a: 0.2 
  rot_a: 0.5
  sync: true